### ISSUE TITLE
Feature request: smooth line drawing between two points

### ISSUE THREAD

**Issue by fwieringen** [gpx-animator/gpx-animator#245]
Hi,

Your tool can be used to create nice map drawing intermezzo's in holiday movies. For example when you take a airplane or a boat. Instead of logging the entire journey, I prefer to draw the track on a map using tools like Google MyMaps. 

Problem is that a track only contains a very limited set of gps locations (see attached file) and no timestamps.

It would be nice if the tool would be able to smoothly draw the line between two gps locations instead of just working through the track by plotting the entire distance from one gps location to the next gps location. 

For example: when I set the Forced Point Time Interval to a specific number and lower the Speedup setting a bit, the tool has quite some frames to actually draw the line between to gps locations. 

I hope you know what I mean :-) Please find attached an example track and movie.
[Smoothlines.zip](https://github.com/zdila/gpx-animator/files/5612850/Smoothlines.zip)

**Comment by thomergil** [comment]
Take a look at https://github.com/remisalmon/gpx_interpolate/ for inspiration.

**Comment by szolnokit** [comment]
Suggestion for implementing this feature:
Try to interpolate the intermediate points outside of "real" GPX ponts, don't simply add to "real" GPS points, Example, do the interplation on the frame rendering "layer".  Not as GPS "database" layer.

Or, if interplation adds the new interplated GPX ponts to "real" GPS ponts, mark these as interpolated.
Need this, because these interplated points are "fake" points, and will be give false information to GPS status "detection" (OK/LOST)..

**Comment by McPringle** [comment]
Thank you very much @fgaignat for your contribution to this issue!
