### ISSUE TITLE
Issue with 'cropped' items inside map

### ISSUE THREAD

**Issue by jbmvl** [gpx-animator/gpx-animator#393]
Hi,

Thank you for your amazing software.

I'm using a custom mapbox with custom tileset (for some train stations) that you can preview here : https://api.mapbox.com/styles/v1/jbmvl/ckyhcifsy7twm14nuwu3wwjbu.html?title=view&access_token=pk.eyJ1IjoiamJtdmwiLCJhIjoiY2tkeXB1azF4MW14ZjMwc2djeTZ0bnQzciJ9.MTwojWi4wo0viGGxdr7jEg&zoomwheel=true&fresh=true#10.02/45.2146/3.2233)

My problem is : it seems that gpx-animator or the API of mapbox doesn't load correctly these tiles and i finish with cropped names for some of my station's names. I tried to change some settings in both but I am not very experienced… Does someone has a idea what the issue could be ? Thanks a lot everyone

![image](https://user-images.githubusercontent.com/736130/149931214-8c8e95cc-8d2f-4938-9ab5-79145e1dc38d.png)

**Comment by McPringle** [comment]
Hi @jbmvl

What do you mean by "cropped names"? For me the names on the map look correct. Or do you mean the names at the edge? That is because the map ends there. The tiles are just JPG or PNG images rendered by the provider of the map (in your case, mapbox). Because the map is "cut" into tiles you will always have cropped names at the edge of the map. There is nothing GPX Animator can do about that.

I hope this answers your question. If not, please reopen this issue and provide more details.
