### ISSUE TITLE
Many of the maps are giving tile errors

### ISSUE THREAD

**Issue by Wellco** [gpx-animator/gpx-animator#423]
Many of the maps are giving tile errors, is there a way the user can fix this?

![Screenshot 2022-10-08 at 22 25 40](https://user-images.githubusercontent.com/5941720/194728317-18af2795-7806-459f-91e8-fd0ae06d9bc1.png)

**Comment by pstorch** [comment]
Had a similar problem, none of the maps were working until I've set the zoom level.

**Comment by Wellco** [comment]
> Had a similar problem, none of the maps were working until I've set the zoom level.

Thanks Peter, Funnily enough when I set the zoom level to anything, maps that were working stop.. Shame because this would give me a great little animation to compliment my presentation

**Comment by McPringle** [comment]
Can you please provide an example? It would be great to get your configuration (File > Save as) and your GPX file. You can either attach it to this issue (as a ZIP file) or send it via email if you want to keep them private: support@gpx-animator.app (please add "GPX Animator Issue #423" to the subject). That makes it much easier for me to replicate your problem.

Btw, the next version of GPX Animator (1.8) will filter unsupported maps (about 50%) so that every listed map should work.

**Comment by McPringle** [comment]
Hi @Wellco, sorry for the long delay, I was very busy the last few months.

Based on the URL in your screenshot, you want to use the "GB: 7th Series (OS7)" map. As the country prefix "GB" indicates, this map is for Great Britain only. You x and y coordinates in the URL look like you are going to request a tile from France. That will not work. You either need to choose a map specifically for France (country prefix "FR") or one of the world-wide maps (country prefix "World").

That should solve your problem. If you have further questions, please add them as a comment here and provide examples like mentioned in my comment above.

Thank you very much for using GPX Animator!
